# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('userID', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('commitTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('userID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('Permission', models.IntegerField()),
                ('approve', models.IntegerField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='eventRelationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eAID', models.IntegerField()),
                ('eBID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uAID', models.CharField(max_length=20)),
                ('uBID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkID', models.IntegerField()),
                ('userID', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=200)),
                ('remarks', models.CharField(max_length=100)),
                ('Permission', models.IntegerField()),
                ('topologyID', models.IntegerField()),
                ('approve', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='linkComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkID', models.IntegerField()),
                ('eventID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
