# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Permission',
            new_name='fin',
        ),
        migrations.RemoveField(
            model_name='event',
            name='remarks',
        ),
        migrations.AddField(
            model_name='event',
            name='permission',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
