# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20171211_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='forked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='commitTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
