# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20180107_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='eventMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('userID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='subEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventID', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='eventRelationship',
        ),
        migrations.DeleteModel(
            name='link',
        ),
        migrations.DeleteModel(
            name='linkComponent',
        ),
        migrations.RemoveField(
            model_name='event',
            name='userID',
        ),
    ]
