# Generated by Django 2.0.1 on 2018-01-18 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20180117_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='startTime',
        ),
        migrations.RemoveField(
            model_name='subevent',
            name='content',
        ),
        migrations.AddField(
            model_name='subevent',
            name='subEventID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
