# Generated by Django 2.0.1 on 2018-01-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20180118_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='subevent',
            name='fin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
